---
- name: Deploy Basic Web Server (Nginx)
  hosts: all
  become: yes
  tasks:

    - name: Install necessary packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - nginx
      
    - name: Copy nginx configuration
     ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Copy index.html
      copy:
        src: templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Enable and start nginx service
      service:
        name: nginx
        enabled: yes
        state: started