---
- name: Install ClamAV
  hosts: all
  become: yes
  tasks:

    - name: Install ClamAV repo
      package:
        name: epel-release
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat" or ansible_os_family == "CentOS" or ansible_os_family == "Fedora"

    - name: Install ClamAV
      package:
        name: clamav
        state: latest
        update_cache: yes
    
    - name: Enable and start clamav-freshclam service
      service:
        name: clamav-freshclam
        enabled: yes
        state: started
    
    - name: Plan a daily scan
      cron:
        name: "ClamAV daily scan"
        minute: 0
        hour: 0
        job: "clamscan -r /"
        state: present
